[build]
  base = "Basic Calculator 2.0"
  command = "npm run build"
  publish = "build"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  for = "/*.css"
    [headers.values]
      Content-Type = "text/css"
  for = "/*.js"
    [headers.values]
      Content-Type = "text/javascript"
